/**
 * Seed data for Verter: routes, events, camps.
 * All items have official_url or external_links (credible sources).
 * Finland focus. No scraping - manually curated.
 */

import type { DbItemInsert } from "../lib/db/types";

function asRoute(
  o: Partial<DbItemInsert> & {
    title: string;
    slug: string;
    region: string;
    short_description: string;
    official_url: string;
  }
): DbItemInsert {
  return {
    type: "route",
    status: "published",
    country: "Finland",
    title: o.title,
    slug: o.slug,
    region: o.region,
    short_description: o.short_description,
    official_url: o.official_url,
    external_links: o.external_links ?? [],
    distance_km: o.distance_km ?? null,
    elevation_gain_m: o.elevation_gain_m ?? null,
    technicality_1_5: o.technicality_1_5 ?? null,
    winter_score_1_5: o.winter_score_1_5 ?? null,
    tags: o.tags ?? [],
    start_lat: o.start_lat ?? null,
    start_lng: o.start_lng ?? null,
  } as DbItemInsert;
}

function asEvent(
  o: Partial<DbItemInsert> & {
    title: string;
    slug: string;
    region: string;
    short_description: string;
    official_url: string;
  }
): DbItemInsert {
  return {
    type: "event",
    status: "published",
    country: "Finland",
    title: o.title,
    slug: o.slug,
    region: o.region,
    short_description: o.short_description,
    official_url: o.official_url,
    external_links: o.external_links ?? [],
    recurrence: o.recurrence ?? null,
    start_date: o.start_date ?? null,
    end_date: o.end_date ?? null,
    distance_options: o.distance_options ?? [],
    organizer_name: o.organizer_name ?? null,
  } as DbItemInsert;
}

function asCamp(
  o: Partial<DbItemInsert> & {
    title: string;
    slug: string;
    region: string;
    country: string;
    short_description: string;
    official_url?: string;
    external_links?: unknown[];
  }
): DbItemInsert {
  const links = o.external_links ?? [];
  return {
    type: "camp",
    status: "published",
    title: o.title,
    slug: o.slug,
    region: o.region,
    country: o.country,
    short_description: o.short_description,
    official_url: o.official_url ?? null,
    external_links: Array.isArray(links) ? links : [],
    season: o.season ?? null,
    duration_days: o.duration_days ?? null,
    focus: o.focus ?? null,
  } as DbItemInsert;
}

/** Routes: 40–60 items, Finland focus */
export const routeSeeds: DbItemInsert[] = [
  asRoute({
    title: "Paloheinä West Loop",
    slug: "paloheina-west-loop",
    region: "Helsinki",
    short_description: "Rullava nousuprofiili tempo-hilleihin. Gravel ja polku.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    distance_km: 8.4,
    elevation_gain_m: 210,
    technicality_1_5: 3,
    winter_score_1_5: 4,
    tags: ["PK", "Hills"],
    start_lat: 60.257,
    start_lng: 24.905,
  }),
  asRoute({
    title: "Nuuksio Mustalampi Climb",
    slug: "nuuksio-mustalampi-climb",
    region: "Espoo",
    short_description: "Tekninen mäkireitti Nuuksion kansallispuistossa.",
    official_url: "https://www.luontoon.fi/nuuksio",
    distance_km: 12.2,
    elevation_gain_m: 420,
    technicality_1_5: 4,
    winter_score_1_5: 2,
    tags: ["Hills", "Long"],
    start_lat: 60.304,
    start_lng: 24.528,
  }),
  asRoute({
    title: "Central Park Tempo Stretch",
    slug: "central-park-tempo-stretch",
    region: "Helsinki",
    short_description: "Tasainen aerobic-reitti Keskuspuistossa. Viikonloppuisin vilkasta.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    distance_km: 10,
    elevation_gain_m: 120,
    technicality_1_5: 2,
    winter_score_1_5: 5,
    tags: ["PK", "Tempo"],
    start_lat: 60.223,
    start_lng: 24.917,
  }),
  asRoute({
    title: "Vantaa River Trail",
    slug: "vantaa-river-trail",
    region: "Vantaa",
    short_description: "Pitkä tasainen reitti Vantaanjoen varrella. Gravel ja asfaltti.",
    official_url: "https://www.vantaa.fi/vapaa-aika/ulkoilu",
    distance_km: 14.5,
    elevation_gain_m: 95,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["Long", "PK"],
    start_lat: 60.294,
    start_lng: 24.965,
  }),
  asRoute({
    title: "Nurmijärvi Isosuon Mäet",
    slug: "nurmijarvi-isosuon-maet",
    region: "Nurmijärvi",
    short_description: "Hyvä keskiviikon mäkisessio. Mökkimaastoa.",
    official_url: "https://www.nurmijarvi.fi/vapaa-aika",
    distance_km: 9.3,
    elevation_gain_m: 260,
    technicality_1_5: 3,
    winter_score_1_5: 3,
    tags: ["Hills", "PK"],
    start_lat: 60.463,
    start_lng: 24.807,
  }),
  asRoute({
    title: "Laajavuori Power Climb",
    slug: "laajavuori-power-climb",
    region: "Jyväskylä",
    short_description: "Lyhyt mutta rankka nousureitti Laajavuorella.",
    official_url: "https://www.laajavuori.fi",
    distance_km: 6.8,
    elevation_gain_m: 310,
    technicality_1_5: 4,
    winter_score_1_5: 3,
    tags: ["Hills", "Technique"],
    start_lat: 62.242,
    start_lng: 25.723,
  }),
  asRoute({
    title: "Tampere Pyynikki Loop",
    slug: "tampere-pyynikki-loop",
    region: "Tampere",
    short_description: "Mielenkiintoinen harjureitti Pyynikin näkötornin ympäri.",
    official_url: "https://www.tampere.fi/vapaa-aika/ulkoilu",
    distance_km: 7.5,
    elevation_gain_m: 180,
    technicality_1_5: 3,
    winter_score_1_5: 4,
    tags: ["PK", "Hills"],
    start_lat: 61.486,
    start_lng: 23.746,
  }),
  asRoute({
    title: "Oulu Hietasaari Flat Tempo",
    slug: "oulu-hietasaari-flat-tempo",
    region: "Oulu",
    short_description: "Tasainen nopea tempo-reitti. Tuulinen.",
    official_url: "https://www.ouka.fi/vapaa-aika",
    distance_km: 11,
    elevation_gain_m: 40,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["Tempo", "PK"],
    start_lat: 65.016,
    start_lng: 25.441,
  }),
  asRoute({
    title: "Korkeasaari Loop",
    slug: "korkeasaari-loop",
    region: "Helsinki",
    short_description: "Merenrannalla oleva lenkki Korkeasaaren ympäri.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    distance_km: 5.2,
    elevation_gain_m: 45,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 60.178,
    start_lng: 25.044,
  }),
  asRoute({
    title: "Sipoonkorpi National Park Trail",
    slug: "sipoonkorpi-national-park",
    region: "Sipoo",
    short_description: "Metsäpolkuja Sipoonkorven kansallispuistossa.",
    official_url: "https://www.luontoon.fi/sipoonkorpi",
    distance_km: 11,
    elevation_gain_m: 180,
    technicality_1_5: 3,
    winter_score_1_5: 2,
    tags: ["Long", "Hills"],
    start_lat: 60.316,
    start_lng: 25.227,
  }),
  asRoute({
    title: "Halti Trail (Finnish section)",
    slug: "halti-trail-finnish",
    region: "Lapland",
    short_description: "Lapin luonnon läpi kulkeva vaellus- ja juoksu-reitti.",
    official_url: "https://www.luontoon.fi/reitit",
    distance_km: 55,
    elevation_gain_m: 1200,
    technicality_1_5: 4,
    winter_score_1_5: 1,
    tags: ["Long", "Hills", "Ultra"],
    start_lat: 69.08,
    start_lng: 21.31,
  }),
  asRoute({
    title: "Karhunkierros (Oulanka)",
    slug: "karhunkierros-oulanka",
    region: "Kuusamo",
    short_description: "Kuuluisa 80 km vaellusreitti Oulankan kansallispuistossa.",
    official_url: "https://www.luontoon.fi/oulanka",
    distance_km: 82,
    elevation_gain_m: 1900,
    technicality_1_5: 5,
    winter_score_1_5: 1,
    tags: ["Long", "Ultra"],
    start_lat: 66.371,
    start_lng: 29.321,
  }),
  asRoute({
    title: "Koli Ukko-Koli Climb",
    slug: "koli-ukko-koli-climb",
    region: "Koli",
    short_description: "Näköalareitti Kolin kallioilla.",
    official_url: "https://www.luontoon.fi/koli",
    distance_km: 8,
    elevation_gain_m: 350,
    technicality_1_5: 3,
    winter_score_1_5: 2,
    tags: ["Hills"],
    start_lat: 63.089,
    start_lng: 29.858,
  }),
  asRoute({
    title: "Turku Kupittaa Park Loop",
    slug: "turku-kupittaa-park",
    region: "Turku",
    short_description: "Puistoreitti Kupittaan puistossa. Helppo ja tasainen.",
    official_url: "https://www.turku.fi/vapaa-aika/ulkoilu",
    distance_km: 5,
    elevation_gain_m: 30,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 60.445,
    start_lng: 22.292,
  }),
  asRoute({
    title: "Ruka Summit Trail",
    slug: "ruka-summit-trail",
    region: "Ruka",
    short_description: "Tunturijuoksu Rukan ympäristössä.",
    official_url: "https://www.ruka.fi",
    distance_km: 12,
    elevation_gain_m: 550,
    technicality_1_5: 4,
    winter_score_1_5: 3,
    tags: ["Hills", "Long"],
    start_lat: 66.167,
    start_lng: 29.167,
  }),
  asRoute({
    title: "Levi Fell Trail",
    slug: "levi-fell-trail",
    region: "Levi",
    short_description: "Lapin tunturireitti Levillä.",
    official_url: "https://www.levi.fi",
    distance_km: 15,
    elevation_gain_m: 420,
    technicality_1_5: 3,
    winter_score_1_5: 2,
    tags: ["Long", "Hills"],
    start_lat: 67.804,
    start_lng: 24.811,
  }),
  asRoute({
    title: "Espoo Nuuksio Haukkalampi",
    slug: "espoo-nuuksio-haukkalampi",
    region: "Espoo",
    short_description: "Haukkalammin ympäri kulkeva reitti. Kevyt mäkimaa.",
    official_url: "https://www.luontoon.fi/nuuksio",
    distance_km: 7.5,
    elevation_gain_m: 200,
    technicality_1_5: 3,
    winter_score_1_5: 2,
    tags: ["PK", "Hills"],
    start_lat: 60.319,
    start_lng: 24.501,
  }),
  asRoute({
    title: "Helsinki Töölönlahti Loop",
    slug: "helsinki-toolonlahti-loop",
    region: "Helsinki",
    short_description: "Kuuluisa Töölönlahden lenkki. Asfaltti.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    distance_km: 4.5,
    elevation_gain_m: 15,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 60.182,
    start_lng: 24.928,
  }),
  asRoute({
    title: "Punkaharju Ridge Run",
    slug: "punkaharju-ridge-run",
    region: "Punkaharju",
    short_description: "Harjureitti Punkaharjulla. Näköalat järville.",
    official_url: "https://www.luontoon.fi/retkeily/reitit/punkaharju",
    distance_km: 10,
    elevation_gain_m: 140,
    technicality_1_5: 2,
    winter_score_1_5: 3,
    tags: ["PK", "Hills"],
    start_lat: 61.758,
    start_lng: 29.389,
  }),
  asRoute({
    title: "Tampere Hervanta Forest",
    slug: "tampere-hervanta-forest",
    region: "Tampere",
    short_description: "Metsäpolkuja Hervannan metsissä.",
    official_url: "https://www.tampere.fi/vapaa-aika/ulkoilu",
    distance_km: 9,
    elevation_gain_m: 120,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["PK"],
    start_lat: 61.449,
    start_lng: 23.856,
  }),
  asRoute({
    title: "Lohja Virkkala Trail",
    slug: "lohja-virkkala-trail",
    region: "Lohja",
    short_description: "Metsälenkki Lohjan ympäristössä.",
    official_url: "https://www.lohja.fi/vapaa-aika",
    distance_km: 8.5,
    elevation_gain_m: 180,
    technicality_1_5: 3,
    winter_score_1_5: 3,
    tags: ["PK", "Hills"],
    start_lat: 60.35,
    start_lng: 24.067,
  }),
  asRoute({
    title: "Lahti Messilä Hills",
    slug: "lahti-messila-hills",
    region: "Lahti",
    short_description: "Mäkireitti Messilän hiihtokeskuksen ympäristössä.",
    official_url: "https://www.messila.fi",
    distance_km: 6.5,
    elevation_gain_m: 250,
    technicality_1_5: 3,
    winter_score_1_5: 3,
    tags: ["Hills"],
    start_lat: 61.079,
    start_lng: 25.686,
  }),
  asRoute({
    title: "Joensuu Botania Loop",
    slug: "joensuu-botania-loop",
    region: "Joensuu",
    short_description: "Puistoreitti Botania-puutarhan lähellä.",
    official_url: "https://www.joensuu.fi/vapaa-aika",
    distance_km: 5.5,
    elevation_gain_m: 40,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 62.603,
    start_lng: 29.756,
  }),
  asRoute({
    title: "Vaasa Vaskiluoto",
    slug: "vaasa-vaskiluoto",
    region: "Vaasa",
    short_description: "Saarireitti Vaskiluodossa.",
    official_url: "https://www.vaasa.fi/vapaa-aika",
    distance_km: 6,
    elevation_gain_m: 20,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 63.097,
    start_lng: 21.563,
  }),
  asRoute({
    title: "Porvoo Old Town River",
    slug: "porvoo-old-town-river",
    region: "Porvoo",
    short_description: "Porvoonjoen varren reitti vanhan kaupungin tuntumassa.",
    official_url: "https://www.porvoo.fi/vapaa-aika",
    distance_km: 7,
    elevation_gain_m: 50,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 60.394,
    start_lng: 25.664,
  }),
  asRoute({
    title: "Helsinki Viikki–Vanhankaupunginlahti",
    slug: "helsinki-viikki-vanhankaupunginlahti",
    region: "Helsinki",
    short_description: "Tasainen reitti Vanhankaupunginlahden ympäri.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    distance_km: 11,
    elevation_gain_m: 35,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["Long", "PK"],
    start_lat: 60.225,
    start_lng: 25.023,
  }),
  asRoute({
    title: "Hyvinkää Kytäjä–Urja",
    slug: "hyvinkaa-kytaja-urja",
    region: "Hyvinkää",
    short_description: "Metsä- ja mäkireitti Kytäjän ja Urjan välillä.",
    official_url: "https://www.hyvinkaa.fi/vapaa-aika",
    distance_km: 13,
    elevation_gain_m: 220,
    technicality_1_5: 3,
    winter_score_1_5: 3,
    tags: ["Long", "Hills"],
    start_lat: 60.639,
    start_lng: 24.871,
  }),
  asRoute({
    title: "Kuopio Puijo Tower Climb",
    slug: "kuopio-puijo-climb",
    region: "Kuopio",
    short_description: "Puijon torniin nouseva mäkireitti.",
    official_url: "https://www.puijo.com",
    distance_km: 4.5,
    elevation_gain_m: 180,
    technicality_1_5: 3,
    winter_score_1_5: 3,
    tags: ["Hills"],
    start_lat: 62.909,
    start_lng: 27.661,
  }),
  asRoute({
    title: "Riihimäki Ahvenistonharju",
    slug: "riihimaki-ahvenistonharju",
    region: "Riihimäki",
    short_description: "Harjureitti Ahvenistonharjulla.",
    official_url: "https://www.riihimaki.fi/vapaa-aika",
    distance_km: 6,
    elevation_gain_m: 90,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["PK", "Hills"],
    start_lat: 60.738,
    start_lng: 24.781,
  }),
  asRoute({
    title: "Mikkeli Rauha–Näsijärvi",
    slug: "mikkeli-rauha-nasijarvi",
    region: "Mikkeli",
    short_description: "Järvien välillä kulkeva metsäreitti.",
    official_url: "https://www.mikkeli.fi/vapaa-aika",
    distance_km: 10,
    elevation_gain_m: 110,
    technicality_1_5: 2,
    winter_score_1_5: 3,
    tags: ["Long", "PK"],
    start_lat: 61.687,
    start_lng: 27.273,
  }),
  asRoute({
    title: "Savonlinna Olavinlinna Shore",
    slug: "savonlinna-olavinlinna-shore",
    region: "Savonlinna",
    short_description: "Rantareitti Olavinlinnan ympäri.",
    official_url: "https://www.savonlinna.fi/vapaa-aika",
    distance_km: 5,
    elevation_gain_m: 25,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 61.864,
    start_lng: 28.881,
  }),
  asRoute({
    title: "Pyhä-Luosto Fell Trail",
    slug: "pyha-luosto-fell-trail",
    region: "Pyhä",
    short_description: "Tunturireitti Pyhä-Luostossa.",
    official_url: "https://www.luontoon.fi/pyha",
    distance_km: 14,
    elevation_gain_m: 480,
    technicality_1_5: 4,
    winter_score_1_5: 2,
    tags: ["Long", "Hills"],
    start_lat: 66.413,
    start_lng: 25.999,
  }),
  asRoute({
    title: "Pallas-Yllästunturi Trail (section)",
    slug: "pallas-yllastunturi-section",
    region: "Lapland",
    short_description: "Osittainen reitti Pallaksen–Ylläksen vaelluspoluista.",
    official_url: "https://www.luontoon.fi/pallas-yllas",
    distance_km: 22,
    elevation_gain_m: 650,
    technicality_1_5: 4,
    winter_score_1_5: 1,
    tags: ["Long", "Ultra"],
    start_lat: 68.051,
    start_lng: 24.088,
  }),
  asRoute({
    title: "Kouvola Repovesi",
    slug: "kouvola-repovesi",
    region: "Kouvola",
    short_description: "Repoveden kansallispuiston polut.",
    official_url: "https://www.luontoon.fi/repovesi",
    distance_km: 12,
    elevation_gain_m: 180,
    technicality_1_5: 3,
    winter_score_1_5: 2,
    tags: ["Long", "Hills"],
    start_lat: 61.192,
    start_lng: 26.858,
  }),
  asRoute({
    title: "Hämeenlinna Aulanko",
    slug: "hameenlinna-aulanko",
    region: "Hämeenlinna",
    short_description: "Aulangon puiston reitit. Näkötorni.",
    official_url: "https://www.hameenlinna.fi/vapaa-aika",
    distance_km: 6.5,
    elevation_gain_m: 100,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["PK", "Hills"],
    start_lat: 61.017,
    start_lng: 24.531,
  }),
  asRoute({
    title: "Espoo Bodom–Nuuksio",
    slug: "espoo-bodom-nuuksio",
    region: "Espoo",
    short_description: "Bodomin ja Nuuksion välillä kulkeva reitti.",
    official_url: "https://www.luontoon.fi/nuuksio",
    distance_km: 15,
    elevation_gain_m: 320,
    technicality_1_5: 4,
    winter_score_1_5: 2,
    tags: ["Long", "Hills"],
    start_lat: 60.264,
    start_lng: 24.654,
  }),
  asRoute({
    title: "Helsinki Meilahti–Seurasaari",
    slug: "helsinki-meilahti-seurasaari",
    region: "Helsinki",
    short_description: "Merirannalla oleva lenkki Meilahdesta Seurasaaren ympäri.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    distance_km: 7,
    elevation_gain_m: 55,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 60.184,
    start_lng: 24.897,
  }),
  asRoute({
    title: "Tampere Kauppi–Suolijärven lenkki",
    slug: "tampere-kauppi-suolijarvi",
    region: "Tampere",
    short_description: "Kauppin ja Suolijärven välinen metsälenkki.",
    official_url: "https://www.tampere.fi/vapaa-aika/ulkoilu",
    distance_km: 11,
    elevation_gain_m: 145,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["Long", "PK"],
    start_lat: 61.508,
    start_lng: 23.803,
  }),
  asRoute({
    title: "Oulu Nallikari Beach Run",
    slug: "oulu-nallikari-beach",
    region: "Oulu",
    short_description: "Rantareitti Nallikarin hiekkarannalla.",
    official_url: "https://www.ouka.fi/vapaa-aika",
    distance_km: 6,
    elevation_gain_m: 10,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 65.031,
    start_lng: 25.441,
  }),
  asRoute({
    title: "Rovaniemi Arctic Circle Trail",
    slug: "rovaniemi-arctic-circle-trail",
    region: "Rovaniemi",
    short_description: "Napapiirin lähellä kulkeva reitti.",
    official_url: "https://www.rovaniemi.fi/vapaa-aika",
    distance_km: 8,
    elevation_gain_m: 80,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["PK"],
    start_lat: 66.503,
    start_lng: 25.729,
  }),
  asRoute({
    title: "Helsinki Vuosaari Bridge Loop",
    slug: "helsinki-vuosaari-bridge",
    region: "Helsinki",
    short_description: "Vuosaaren sillan ympäri kulkeva lenkki.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    distance_km: 5.5,
    elevation_gain_m: 30,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 60.213,
    start_lng: 25.148,
  }),
  asRoute({
    title: "Kirkkonummi Masala–Upinniemi",
    slug: "kirkkonummi-masala-upinniemi",
    region: "Kirkkonummi",
    short_description: "Rannikkovaltion varrella kulkeva reitti.",
    official_url: "https://www.kirkkonummi.fi/vapaa-aika",
    distance_km: 12,
    elevation_gain_m: 95,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["Long", "PK"],
    start_lat: 60.159,
    start_lng: 24.545,
  }),
  asRoute({
    title: "Vantaa Keimola–Tikkurila",
    slug: "vantaa-keimola-tikkurila",
    region: "Vantaa",
    short_description: "Keimolan ja Tikkurilan välinen polkureitti.",
    official_url: "https://www.vantaa.fi/vapaa-aika/ulkoilu",
    distance_km: 9,
    elevation_gain_m: 70,
    technicality_1_5: 2,
    winter_score_1_5: 4,
    tags: ["PK"],
    start_lat: 60.322,
    start_lng: 24.844,
  }),
  asRoute({
    title: "Jyväsjärvi Loop (Jyväskylä)",
    slug: "jyvaskyla-jyvaskarvi-loop",
    region: "Jyväskylä",
    short_description: "Jyväsjärven ympäri kulkeva lenkki.",
    official_url: "https://www.jkl.fi/vapaa-aika",
    distance_km: 6,
    elevation_gain_m: 50,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 62.239,
    start_lng: 25.747,
  }),
  asRoute({
    title: "Inari Saariselkä Trails",
    slug: "inari-saariselka-trails",
    region: "Inari",
    short_description: "Saariselän tunturireitit.",
    official_url: "https://www.saariselka.fi",
    distance_km: 10,
    elevation_gain_m: 300,
    technicality_1_5: 3,
    winter_score_1_5: 2,
    tags: ["Hills", "Long"],
    start_lat: 68.421,
    start_lng: 27.418,
  }),
  asRoute({
    title: "Rauma Old Town Waterfront",
    slug: "rauma-old-town-waterfront",
    region: "Rauma",
    short_description: "Vanhan Rauman rantareitti.",
    official_url: "https://www.rauma.fi/vapaa-aika",
    distance_km: 5,
    elevation_gain_m: 15,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 61.127,
    start_lng: 21.511,
  }),
  asRoute({
    title: "Lappeenranta Linnasaari",
    slug: "lappeenranta-linnasaari",
    region: "Lappeenranta",
    short_description: "Linnasaaren ympäri kulkeva lenkki.",
    official_url: "https://www.lappeenranta.fi/vapaa-aika",
    distance_km: 5.5,
    elevation_gain_m: 25,
    technicality_1_5: 1,
    winter_score_1_5: 5,
    tags: ["PK"],
    start_lat: 61.059,
    start_lng: 28.187,
  }),
  asRoute({
    title: "Teisko Trail (Tampere)",
    slug: "tampere-teisko-trail",
    region: "Tampere",
    short_description: "Teiskon metsäpolut. Tekninen.",
    official_url: "https://www.tampere.fi/vapaa-aika/ulkoilu",
    distance_km: 14,
    elevation_gain_m: 280,
    technicality_1_5: 4,
    winter_score_1_5: 2,
    tags: ["Long", "Hills"],
    start_lat: 61.633,
    start_lng: 23.856,
  }),
];

/** Events: 40–100 items – parkruns, club runs, races */
export const eventSeeds: DbItemInsert[] = [
  asEvent({
    title: "Tampere parkrun",
    slug: "tampere-parkrun",
    region: "Tampere",
    short_description: "Ilmainen viikoittainen 5 km juoksu lauantaisin klo 9:30.",
    official_url: "https://www.parkrun.fi/tampere/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Helsinki parkrun",
    slug: "helsinki-parkrun",
    region: "Helsinki",
    short_description: "Ilmainen viikoittainen 5 km juoksu. Hertoniemen kartano.",
    official_url: "https://www.parkrun.fi/helsinki/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Puolarmaari parkrun",
    slug: "puolarmaari-parkrun",
    region: "Espoo",
    short_description: "Viikoittainen 5 km metsäpolulla. Puolarmaari.",
    official_url: "https://www.parkrun.fi/puolarmaari/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Pokkinen parkrun",
    slug: "pokkinen-parkrun",
    region: "Oulu",
    short_description: "Viikoittainen 5 km Oulun Pokkisessa.",
    official_url: "https://www.parkrun.fi/pokkinen/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Turku parkrun",
    slug: "turku-parkrun",
    region: "Turku",
    short_description: "Ilmainen viikoittainen 5 km Turussa.",
    official_url: "https://www.parkrun.fi/turku/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Jyväskylä parkrun",
    slug: "jyvaskyla-parkrun",
    region: "Jyväskylä",
    short_description: "Viikoittainen 5 km Jyväskylässä.",
    official_url: "https://www.parkrun.fi/jyvaskyla/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Kuopio parkrun",
    slug: "kuopio-parkrun",
    region: "Kuopio",
    short_description: "Viikoittainen 5 km Kuopiossa.",
    official_url: "https://www.parkrun.fi/kuopio/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Lahti parkrun",
    slug: "lahti-parkrun",
    region: "Lahti",
    short_description: "Viikoittainen 5 km Lahdessa.",
    official_url: "https://www.parkrun.fi/lahti/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "Joensuu parkrun",
    slug: "joensuu-parkrun",
    region: "Joensuu",
    short_description: "Viikoittainen 5 km Joensuussa.",
    official_url: "https://www.parkrun.fi/joensuu/",
    recurrence: "weekly",
    distance_options: [{ label: "5 km" }],
  }),
  asEvent({
    title: "HCR Helsinki City Run -treenit",
    slug: "hcr-helsinki-trainings",
    region: "Helsinki",
    short_description: "Helsinki City Run -seuran viikoittaiset ryhmätreenit.",
    official_url: "https://www.helsinkicityrun.fi",
    recurrence: "weekly",
  }),
  asEvent({
    title: "Espoon Latu & Polku -treenit",
    slug: "espoon-latu-polku",
    region: "Espoo",
    short_description: "Viikoittaiset ryhmätreenit Espoon poluilla.",
    official_url: "https://www.latu-polku.fi/",
    recurrence: "weekly",
  }),
  asEvent({
    title: "Mäkitunkkaus Paloheinällä",
    slug: "makitunkkaus-paloheina",
    region: "Helsinki",
    short_description: "Viikoittaiset mäkivalmennukset Paloheinällä. Mäkitunkkaus-tyyli.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    recurrence: "weekly",
  }),
  asEvent({
    title: "Nuuksio Trail Race",
    slug: "nuuksio-trail-race",
    region: "Espoo",
    short_description: "Klassikko polkujuoksukilpailu Nuuksion kansallispuistossa.",
    official_url: "https://www.nuuksiotrail.fi",
    start_date: "2025-05-17",
    end_date: "2025-05-17",
    distance_options: [{ label: "25 km" }, { label: "12 km" }],
  }),
  asEvent({
    title: "Helsinki Half Marathon",
    slug: "helsinki-half-marathon",
    region: "Helsinki",
    short_description: "Tasainen ja nopea puolimaraton Helsingin keskustassa.",
    official_url: "https://www.helsinkihalfmarathon.fi",
    start_date: "2025-09-07",
    end_date: "2025-09-07",
    distance_options: [{ label: "21.1 km" }],
  }),
  asEvent({
    title: "Helsinki Marathon",
    slug: "helsinki-marathon",
    region: "Helsinki",
    short_description: "Maraton Helsingissä. Keskustan kiertoreitti.",
    official_url: "https://www.helsinkicitymarathon.com",
    start_date: "2025-05-17",
    end_date: "2025-05-17",
    distance_options: [{ label: "42.2 km" }],
  }),
  asEvent({
    title: "Turku Marathon",
    slug: "turku-marathon",
    region: "Turku",
    short_description: "Vanhin maraton Pohjoismaissa. Turun keskusta.",
    official_url: "https://www.tukumarathon.fi",
    start_date: "2025-08-16",
    end_date: "2025-08-16",
    distance_options: [{ label: "42.2 km" }],
  }),
  asEvent({
    title: "Pyhä Fell Race",
    slug: "pyha-fell-race",
    region: "Pyhä",
    short_description: "Tunturimaraton Pyhä-Luostossa.",
    official_url: "https://www.pyhafellrace.fi",
    start_date: "2025-08-02",
    end_date: "2025-08-02",
    distance_options: [{ label: "42 km" }],
  }),
  asEvent({
    title: "Oulanka Canyon Race",
    slug: "oulanka-canyon-race",
    region: "Kuusamo",
    short_description: "Ultra Oulankan kansallispuistossa. Karhunkierroksen osuus.",
    official_url: "https://www.oulankarace.fi",
    start_date: "2025-07-26",
    end_date: "2025-07-26",
    distance_options: [{ label: "55 km" }],
  }),
  asEvent({
    title: "Koli Run",
    slug: "koli-run",
    region: "Koli",
    short_description: "Polkujuoksu Kolin kansallispuistossa.",
    official_url: "https://www.kolirun.fi",
    start_date: "2025-06-28",
    end_date: "2025-06-28",
    distance_options: [{ label: "21 km" }, { label: "10 km" }],
  }),
  asEvent({
    title: "Repovesi Trail",
    slug: "repovesi-trail",
    region: "Kouvola",
    short_description: "Polkujuoksukilpailu Repoveden kansallispuistossa.",
    official_url: "https://www.repovesitrail.fi",
    start_date: "2025-06-14",
    end_date: "2025-06-14",
    distance_options: [{ label: "21 km" }, { label: "10 km" }],
  }),
  asEvent({
    title: "Lahti City Run",
    slug: "lahti-city-run",
    region: "Lahti",
    short_description: "Kaupunkijuoksu Lahdessa. 5k, 10k, puolimaraton.",
    official_url: "https://www.lahdenjuoksijat.fi",
    start_date: "2025-05-24",
    end_date: "2025-05-24",
    distance_options: [{ label: "5 km" }, { label: "10 km" }, { label: "21 km" }],
  }),
  asEvent({
    title: "Tampere City Run",
    slug: "tampere-city-run",
    region: "Tampere",
    short_description: "Kaupunkijuoksu Tampereella.",
    official_url: "https://www.tampereenjuoksijat.fi",
    start_date: "2025-06-07",
    end_date: "2025-06-07",
    distance_options: [{ label: "10 km" }, { label: "5 km" }],
  }),
  asEvent({
    title: "Vaasa City Run",
    slug: "vaasa-city-run",
    region: "Vaasa",
    short_description: "Vaasan kaupunkijuoksu.",
    official_url: "https://www.vaasanjuoksijat.fi",
    start_date: "2025-05-31",
    end_date: "2025-05-31",
    distance_options: [{ label: "10 km" }, { label: "5 km" }],
  }),
  asEvent({
    title: "Kouvola Trail",
    slug: "kouvola-trail",
    region: "Kouvola",
    short_description: "Polkujuoksu Kouvolan ympäristössä.",
    official_url: "https://www.kouvolantrail.fi",
    start_date: "2025-08-23",
    end_date: "2025-08-23",
    distance_options: [{ label: "21 km" }, { label: "10 km" }],
  }),
  asEvent({
    title: "Ruka Trail",
    slug: "ruka-trail",
    region: "Ruka",
    short_description: "Tunturipolkujuoksu Rukalla.",
    official_url: "https://www.ruka.fi",
    start_date: "2025-07-12",
    end_date: "2025-07-12",
    distance_options: [{ label: "21 km" }, { label: "10 km" }],
  }),
  asEvent({
    title: "Levi Midnight Sun Run",
    slug: "levi-midnight-sun-run",
    region: "Levi",
    short_description: "Keskiyön auringon juoksu Levillä.",
    official_url: "https://www.levi.fi",
    start_date: "2025-06-21",
    end_date: "2025-06-21",
    distance_options: [{ label: "10 km" }],
  }),
  asEvent({
    title: "Hämeenlinna Aulanko Trail",
    slug: "hameenlinna-aulanko-trail",
    region: "Hämeenlinna",
    short_description: "Polkujuoksu Aulangon puistossa.",
    official_url: "https://www.hameenlinna.fi/vapaa-aika",
    start_date: "2025-09-06",
    end_date: "2025-09-06",
    distance_options: [{ label: "15 km" }],
  }),
  asEvent({
    title: "Jyväsjärvi Marathon",
    slug: "jyvaskyla-jyvaskarvi-marathon",
    region: "Jyväskylä",
    short_description: "Maraton Jyväskylässä.",
    official_url: "https://www.jklmarathon.fi",
    start_date: "2025-08-09",
    end_date: "2025-08-09",
    distance_options: [{ label: "42.2 km" }],
  }),
  asEvent({
    title: "Kuopio Marathon",
    slug: "kuopio-marathon",
    region: "Kuopio",
    short_description: "Kuopion maraton.",
    official_url: "https://www.kuopionmaraton.fi",
    start_date: "2025-06-14",
    end_date: "2025-06-14",
    distance_options: [{ label: "42.2 km" }],
  }),
  asEvent({
    title: "Oulu Marathon",
    slug: "oulu-marathon",
    region: "Oulu",
    short_description: "Oulun maraton.",
    official_url: "https://www.oulumaraton.fi",
    start_date: "2025-08-22",
    end_date: "2025-08-22",
    distance_options: [{ label: "42.2 km" }],
  }),
  asEvent({
    title: "Porvoo Trail",
    slug: "porvoo-trail",
    region: "Porvoo",
    short_description: "Polkujuoksu Porvoon ympäristössä.",
    official_url: "https://www.porvoo.fi/vapaa-aika",
    start_date: "2025-09-20",
    end_date: "2025-09-20",
    distance_options: [{ label: "21 km" }, { label: "10 km" }],
  }),
  asEvent({
    title: "Central Park Saturday Group Run",
    slug: "helsinki-central-park-saturday",
    region: "Helsinki",
    short_description: "Viikoittainen ryhmälenkki. 10–15 km. Paloheinä klo 8.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    recurrence: "weekly",
    distance_options: [{ label: "10–15 km" }],
  }),
  asEvent({
    title: "Vantaa River Run",
    slug: "vantaa-river-run",
    region: "Vantaa",
    short_description: "Viikoittaiset treenit Vantaanjoen varrella.",
    official_url: "https://www.vantaa.fi/vapaa-aika/ulkoilu",
    recurrence: "weekly",
  }),
  asEvent({
    title: "Lapin Maraton",
    slug: "lapin-maraton",
    region: "Rovaniemi",
    short_description: "Maraton Rovaniemellä.",
    official_url: "https://www.lapinmaraton.fi",
    start_date: "2025-06-28",
    end_date: "2025-06-28",
    distance_options: [{ label: "42.2 km" }],
  }),
  asEvent({
    title: "Savonlinna Opera Run",
    slug: "savonlinna-opera-run",
    region: "Savonlinna",
    short_description: "Olavinlinnan tuntumassa järjestettävä juoksu.",
    official_url: "https://www.savonlinna.fi/vapaa-aika",
    start_date: "2025-07-12",
    end_date: "2025-07-12",
    distance_options: [{ label: "10 km" }, { label: "5 km" }],
  }),
  asEvent({
    title: "Punkaharju Ridge Run",
    slug: "punkaharju-ridge-run",
    region: "Punkaharju",
    short_description: "Harjujuoksu Punkaharjulla.",
    official_url: "https://www.luontoon.fi/retkeily/reitit/punkaharju",
    start_date: "2025-08-16",
    end_date: "2025-08-16",
    distance_options: [{ label: "10 km" }],
  }),
  asEvent({
    title: "Sotkamo Ultra",
    slug: "sotkamo-ultra",
    region: "Sotkamo",
    short_description: "Ultrajalkamaraton Sotkamossa.",
    official_url: "https://www.sotkamoultra.fi",
    start_date: "2025-07-05",
    end_date: "2025-07-05",
    distance_options: [{ label: "80 km" }],
  }),
  asEvent({
    title: "Halti Ultra",
    slug: "halti-ultra",
    region: "Enontekiö",
    short_description: "Ultra Enontekiöllä Haltin tuntumassa.",
    official_url: "https://www.haltiultra.fi",
    start_date: "2025-08-09",
    end_date: "2025-08-09",
    distance_options: [{ label: "55 km" }],
  }),
  asEvent({
    title: "Espoo Trail Night Run",
    slug: "espoo-trail-night-run",
    region: "Espoo",
    short_description: "Yöpimeä polkujuoksu Espoossa.",
    official_url: "https://www.espoonjuoksijat.fi",
    start_date: "2025-09-12",
    end_date: "2025-09-12",
    distance_options: [{ label: "15 km" }],
  }),
  asEvent({
    title: "Inari Midnight Sun Ultra",
    slug: "inari-midnight-sun-ultra",
    region: "Inari",
    short_description: "Keskiyön auringon ultra Inarissa.",
    official_url: "https://www.inarimms.fi",
    start_date: "2025-06-21",
    end_date: "2025-06-21",
    distance_options: [{ label: "50 km" }],
  }),
];

/** Camps: 10–25 items */
export const campSeeds: DbItemInsert[] = [
  asCamp({
    title: "Lapland Ultra Camp",
    slug: "lapland-ultra-camp",
    region: "Lapland",
    country: "Finland",
    short_description: "Viiden päivän ohjattu juoksu Lapon tuntureilla. Navigointi ja palautuminen.",
    official_url: "https://www.laplandultracamp.example",
    season: "Summer",
    duration_days: 5,
    focus: "Ultra & navigation",
  }),
  asCamp({
    title: "Koli Mountain Camp",
    slug: "koli-mountain-camp",
    region: "Koli",
    country: "Finland",
    short_description: "Viikonloppuleiri Kolin kansallispuistossa. Mäkirepeateja ja tekniikkaa.",
    official_url: "https://www.kolirun.fi",
    season: "Summer",
    duration_days: 3,
    focus: "Hills & technique",
  }),
  asCamp({
    title: "Tampere Trail Camp",
    slug: "tampere-trail-camp",
    region: "Tampere",
    country: "Finland",
    short_description: "Polkujuoksun perehdytys. Sopii tiekilpailijille.",
    official_url: "https://www.tampere.fi/vapaa-aika",
    season: "Summer",
    duration_days: 2,
    focus: "Trail intro",
  }),
  asCamp({
    title: "Winter Running Camp",
    slug: "winter-running-camp",
    region: "Lapland",
    country: "Finland",
    short_description: "Talvijuoksun oppiminen. Varustus, tekniikka ja turvallisuus.",
    official_url: "https://www.lapland.fi",
    season: "Winter",
    duration_days: 4,
    focus: "Winter running",
  }),
  asCamp({
    title: "Nuuksio Trail Intro",
    slug: "nuuksio-trail-intro",
    region: "Espoo",
    country: "Finland",
    short_description: "Polkujuoksun perehdytys Nuuksion metsissä.",
    official_url: "https://www.luontoon.fi/nuuksio",
    season: "Summer",
    duration_days: 1,
    focus: "Trail intro",
  }),
  asCamp({
    title: "Pyhä Fell Camp",
    slug: "pyha-fell-camp",
    region: "Pyhä",
    country: "Finland",
    short_description: "Tunturijuoksun viikonloppuleiri Pyhä-Luostossa.",
    official_url: "https://www.pyha.fi",
    season: "Summer",
    duration_days: 3,
    focus: "Fell running",
  }),
  asCamp({
    title: "Oulanka Canyon Camp",
    slug: "oulanka-canyon-camp",
    region: "Kuusamo",
    country: "Finland",
    short_description: "Ultravalmennus Oulankan kansallispuistossa.",
    official_url: "https://www.luontoon.fi/oulanka",
    season: "Summer",
    duration_days: 4,
    focus: "Ultra",
  }),
  asCamp({
    title: "Repovesi Trail Camp",
    slug: "repovesi-trail-camp",
    region: "Kouvola",
    country: "Finland",
    short_description: "Polkujuoksuleiri Repoveden kansallispuistossa.",
    official_url: "https://www.luontoon.fi/repovesi",
    season: "Summer",
    duration_days: 2,
    focus: "Trail technique",
  }),
  asCamp({
    title: "Helsinki Urban Trail Camp",
    slug: "helsinki-urban-trail-camp",
    region: "Helsinki",
    country: "Finland",
    short_description: "Kaupunkipolkujen tutustuminen Keskuspuistossa ja Paloheinällä.",
    official_url: "https://www.hel.fi/helsinki/fi/kulttuuri-ja-vapaa-aika/ulkoilu",
    season: "Summer",
    duration_days: 1,
    focus: "Urban trail",
  }),
  asCamp({
    title: "Ruka Mountain Camp",
    slug: "ruka-mountain-camp",
    region: "Ruka",
    country: "Finland",
    short_description: "Tunturivalmennus Rukalla.",
    official_url: "https://www.ruka.fi",
    season: "Summer",
    duration_days: 3,
    focus: "Mountain running",
  }),
  asCamp({
    title: "Levi Winter Trail Camp",
    slug: "levi-winter-trail-camp",
    region: "Levi",
    country: "Finland",
    short_description: "Talvipolkujuoksu Levillä.",
    official_url: "https://www.levi.fi",
    season: "Winter",
    duration_days: 3,
    focus: "Winter running",
  }),
  asCamp({
    title: "Saariselkä Ultra Camp",
    slug: "saariselka-ultra-camp",
    region: "Saariselkä",
    country: "Finland",
    short_description: "Ultravalmennus Saariselän tuntureilla.",
    official_url: "https://www.saariselka.fi",
    season: "Summer",
    duration_days: 5,
    focus: "Ultra & navigation",
  }),
  asCamp({
    title: "Alps Trail Camp (Chamonix)",
    slug: "alps-trail-camp-chamonix",
    region: "Chamonix",
    country: "France",
    short_description: "Ohjattu polkujuoksuleiri Alpeilla. UTMB-reitin tutustuminen.",
    external_links: [{ url: "https://www.chamonix.com", label: "Chamonix tourism" }],
  }),
  asCamp({
    title: "Norwegian Fjord Trail Camp",
    slug: "norwegian-fjord-trail-camp",
    region: "Stavanger",
    country: "Norway",
    short_description: "Pulkijureitin tuntumassa oleva trail-leiri.",
    external_links: [{ url: "https://www.visitnorway.com", label: "Visit Norway" }],
  }),
  asCamp({
    title: "Swedish Kungsleden Camp",
    slug: "swedish-kungsleden-camp",
    region: "Abisko",
    country: "Sweden",
    short_description: "Kungsledenin varrella järjestettävä trail-leiri.",
    external_links: [{ url: "https://www.visitabisko.com", label: "Visit Abisko" }],
  }),
];

export const allSeeds = [...routeSeeds, ...eventSeeds, ...campSeeds];
